name: Test image

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 1

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: curl -s https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
      - run: ./test.sh
